"""Math / data / eval utilities.

Resolved lazily (see :mod:`helm._lazy`) so that importing ``arcosh`` for the
Lorentz manifold does not also import ``sklearn``, ``networkx`` and friends.
"""

from helm._lazy import install_lazy

_EXPORTS = {
    "Arcosh": ".math_utils",
    "Arsinh": ".math_utils",
    "Artanh": ".math_utils",
    "MarginLoss": ".eval_utils",
    "acc_f1": ".eval_utils",
    "arcosh": ".math_utils",
    "arsinh": ".math_utils",
    "artanh": ".math_utils",
    "augment": ".data_utils",
    "bin_feat": ".data_utils",
    "build_distance": ".data_utils",
    "categorize_params": ".pre_utils",
    "convert_hgnn_adj": ".h2h_data_utils",
    "cosh": ".math_utils",
    "distortion": ".distortions",
    "distortion_entry": ".distortions",
    "distortion_row": ".distortions",
    "entry_is_good": ".distortions",
    "gather_across_processes": ".distributed",
    "get_activation": ".pre_utils",
    "get_lr_scheduler": ".pre_utils",
    "get_optimizer": ".pre_utils",
    "get_params": ".pre_utils",
    "get_rank": ".distributed",
    "get_stiefel_optimizer": ".pre_utils",
    "get_world_size": ".distributed",
    "gpu_mem_usage": ".distributed",
    "h2h_load_data": ".h2h_data_utils",
    "init_weight": ".pre_utils",
    "is_main_process": ".distributed",
    "launch": ".distributed",
    "load_citation_data": ".data_utils",
    "load_data": ".data_utils",
    "load_data_airport": ".data_utils",
    "load_data_lp": ".data_utils",
    "load_data_md": ".data_utils",
    "load_data_nc": ".data_utils",
    "load_synthetic_data": ".data_utils",
    "load_synthetic_md_data": ".data_utils",
    "map_row": ".distortions",
    "map_score": ".distortions",
    "map_via_edges": ".distortions",
    "mask_edges": ".data_utils",
    "nn_init": ".pre_utils",
    "normalize": ".data_utils",
    "normalize_weight": ".pre_utils",
    "pad_sequence": ".pre_utils",
    "parse_index_file": ".data_utils",
    "preprocess_graph": ".data_utils",
    "process": ".data_utils",
    "set_seed": ".pre_utils",
    "set_up_optimizer_scheduler": ".pre_utils",
    "sinh": ".math_utils",
    "sparse_mx_to_torch_sparse_tensor": ".data_utils",
    "split_data": ".data_utils",
    "synchronize": ".distributed",
    "tanh": ".math_utils",
    "th_dot": ".pre_utils",
}

install_lazy(__name__, globals(), _EXPORTS)
